spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: syimyk

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080